### ISSUE TITLE
Include only files that match pattern

### ISSUE THREAD

**Issue by leodr** [simonw/files-to-prompt#28]
Hi, nice project, thanks for building!

I was working on an iOS project yesterday, where there are lots of random JSON files for assets and plist files and whatnot in the project directory, but I'd only like to include `.swift` files in the prompt.

I think an option like `--include-only` or maybe just `--only` would be nice. It could be made either or with the ignore options so there can't be rule clashing.

**Comment by simonw** [comment]
I just found myself wanting exactly the same thing - I so often want to say "just include the .py and .md` files", for example.

I'm going with `-e py -e md` - where `-e` is short for `--extension`.

**Comment by simonw** [comment]
`fd` is an example of a command that uses `-e` for this: https://github.com/sharkdp/fd/blob/master/README.md#searching-for-a-particular-file-extension
