### ISSUE TITLE
recommendation

### ISSUE THREAD

**Issue by heresyrj** [simonw/files-to-prompt#3]
I write both python project and web application.
It would be great if it detects the .gitignore file and respect the rules set in that file. 
Also ignore node_modules for npm, coverage for jest etc.

**Comment by simonw** [comment]
`.gitignore` is supported - which should help with `node_modules` etc as well.

**Comment by jefftriplett** [comment]
Sharing this in case it's helpful. I ended up with a really long list for my Django app: 

```bash
    files-to-prompt \
        --cxml \
        --ignore "*.cxml" \
        --ignore "*.ico" \
        --ignore "*.png" \
        --ignore "*.toml" \
        --ignore "*.webmanifest" \
        --ignore "*.xml" \
        --ignore "00*.py" \
        --ignore "__init__.py" \
        --ignore "compose*" \
        --ignore "conftest.py" \
        --ignore "files-to-xml.py" \
        --ignore "frontend/*" \
        --ignore "justfile" \
        --ignore "LICENSE" \
        --ignore "manage.py" \
        --ignore "requirements.*" \
        --ignore "settings.py" \
        --ignore "wsgi.py" \
        --output _claude.cxml \
        .
```

Ideally, having a `.claudeignore` or files-to-prompt named config would go a long way. 

These files would not be in a `.gitignore`, but I don't think it's useful context to pass 20 migration files to Claude.
